version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/site
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user